# Modrinth CI Konfiguration für KatanaPlus

project_id = "katanaplus"
game_versions = ["1.20.1"]
loaders = ["forge"]
upload_file = "build/libs/KatanaPlus-1.0.0.jar"
version_name = "KatanaPlus 1.0.0"
version_number = "1.0.0"
changelog = "Initial release with custom Katana."
license = "ARR"
dependencies = [
  { project = "forge", version = "47.3.0", dependency_type = "required" },
  { project = "create", dependency_type = "required" }
]
