name: Build & Publish Forge Mod

on:
  push:
    branches: [ main ]   # läuft bei jedem Push auf main
  workflow_dispatch:      # manuell auslösbar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Ensure artifact exists
        run: test -f build/libs/*.jar

      - name: Upload artifact for other jobs
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar

      # 👇 Version aus gradle.properties holen
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep "^mod_version" gradle.properties | cut -d'=' -f2 | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Save version for other jobs
        run: echo "MOD_VERSION=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV

  modrinth:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built jar
        uses: actions/download-artifact@v3
        with:
          name: mod-jar
          path: .

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2.1.3
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: Jcl8pfJY
          version: ${{ env.MOD_VERSION }}
          changelog: ${{ github.event.head_commit.message }}
          loaders: forge
          game-versions: "1.20.1"
          files: ./*.jar

  github-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built jar
        uses: actions/download-artifact@v3
        with:
          name: mod-jar
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.MOD_VERSION }}
          name: Release ${{ env.MOD_VERSION }}
          body: ${{ github.event.head_commit.message }}
          files: ./*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
